### ISSUE TITLE
Provide empty migration scripts for update from 2.2 to 2.3

### ISSUE THREAD

**Issue by wolfgangwalther** [nmandery/pg_byteamagic#3]
The latest version bump to 2.3 broke the deployment for me. My migration script does something like this automatically:

```
ALTER EXTENSION byteamagic UPDATE;
```

This updates the extension to the latest version.

But this fails with an error like "no update path found for 2.2 to 2.3". I think there just needs to be an empty .sql file for a migration path with those two version numbers.

Can you add one?

**Comment by nmandery** [comment]
I see - I messed up the migration scripts (documented at https://www.postgresql.org/docs/current/extend-extensions.html). 

As I can not replace the released version v0.2.3, a new v0.2.4 will be released including the migration scripts.

**Comment by nmandery** [comment]
v0.2.4 is now on pgxn
